options:
  nagios_context:
    default: "juju"
    type: string
    description: |
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      Comma separated list of nagios servicegroups for the service checks.
  enable-auto-restarts:
    type: boolean
    default: True
    description: |
      Allow the charm and packages to restart services automatically when
      required.
