name: Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  functest:
    name: Functional Tests
    runs-on: [self-hosted, linux, X64, large, noble]
    steps:
      - name: debug
        run: |
          ip li
          ip a
          sudo iptables -nvL
          sudo iptables -t nat -nvL
          sudo nft list ruleset
          ping 1.1.1.1 &
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
          sleep 5
          killall ping
